#!/usr/bin/env bash
# Extract Claude Code OAuth token from local credentials and write to .env
#
# Supports:
#   macOS  — reads from Keychain (security command)
#   Linux  — reads from ~/.claude/.credentials.json
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/../.env"

TOKEN=""

case "$(uname -s)" in
  Darwin)
    TOKEN=$(security find-generic-password -s "Claude Code-credentials" -a "$(whoami)" -w 2>/dev/null \
      | python3 -c "import sys,json; d=json.load(sys.stdin); print(d['claudeAiOauth']['accessToken'])" 2>/dev/null || true)
    ;;
  Linux)
    CRED_FILE="${HOME}/.claude/.credentials.json"
    if [ -f "$CRED_FILE" ]; then
      TOKEN=$(python3 -c "import json; d=json.load(open('${CRED_FILE}')); print(d['claudeAiOauth']['accessToken'])" 2>/dev/null || true)
    fi
    ;;
esac

if [ -z "$TOKEN" ]; then
  echo "Error: Could not extract OAuth token." >&2
  echo "" >&2
  echo "Options:" >&2
  echo "  1. Run 'claude auth login' first, then re-run this script" >&2
  echo "  2. Run 'claude setup-token' and paste the token into .env manually:" >&2
  echo "       CLAUDE_CODE_OAUTH_TOKEN=sk-ant-oat01-..." >&2
  echo "  3. Use an Anthropic API key instead:" >&2
  echo "       ANTHROPIC_API_KEY=sk-ant-api03-..." >&2
  exit 1
fi

if [ -f "$ENV_FILE" ]; then
  # Preserve existing lines (e.g. ANTHROPIC_API_KEY) while updating the token
  if grep -q '^CLAUDE_CODE_OAUTH_TOKEN=' "$ENV_FILE" 2>/dev/null; then
    sed -i.bak "s|^CLAUDE_CODE_OAUTH_TOKEN=.*|CLAUDE_CODE_OAUTH_TOKEN=${TOKEN}|" "$ENV_FILE"
    rm -f "${ENV_FILE}.bak"
  else
    echo "CLAUDE_CODE_OAUTH_TOKEN=${TOKEN}" >> "$ENV_FILE"
  fi
else
  cat > "$ENV_FILE" <<EOF
# Auto-generated by scripts/refresh-token.sh
CLAUDE_CODE_OAUTH_TOKEN=${TOKEN}
EOF
fi

echo "Token written to .env"
