#!/usr/bin/env bash
# Extract Claude Code OAuth token from macOS Keychain and write to .env
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/../.env"

TOKEN=$(security find-generic-password -s "Claude Code-credentials" -a "$(whoami)" -w 2>/dev/null \
  | python3 -c "import sys,json; d=json.load(sys.stdin); print(d['claudeAiOauth']['accessToken'])" 2>/dev/null)

if [ -z "$TOKEN" ]; then
  echo "Error: Could not extract OAuth token from Keychain." >&2
  echo "Run 'claude auth login' first to authenticate." >&2
  exit 1
fi

cat > "$ENV_FILE" <<EOF
# Auto-generated by scripts/refresh-token.sh
CLAUDE_CODE_OAUTH_TOKEN=${TOKEN}
EOF

echo "Token written to .env"
